### ISSUE TITLE
`FactorNodeOptions` are not unique

### ISSUE THREAD

**Issue by wouterwln** [ReactiveBayes/GraphPPL.jl#132]
Investigated with @bvdmitri , the `FactorNodeOptions` that are being attached to every node are actually not unique. This is now fixed by deepcopy'ing them, which is a really ugly solution, so we should look at this. Bug is isolated to be in the code generated by the node macro. There, we create a `FactorNodeOptions` object and pass it into `prepare_options`. I suspect that `FactorNodeOptions` are not uniquely created in loops for every iteration of the loop, but I don't have proof.

**Comment by bvdmitri** [comment]
Going to be addressed by https://github.com/ReactiveBayes/GraphPPL.jl/tree/dev-4.0.0-plugins-system
