### ISSUE TITLE
Interface aliases should be possible

### ISSUE THREAD

**Issue by wouterwln** [ReactiveBayes/GraphPPL.jl#143]
Maybe through custom struct in `StaticInterfaces`? But could make interfaces slower as is

**Comment by bvdmitri** [comment]
@wouterwln 
```julia
y[i] ~ MvNormal(mean = m, covariance = C)
y[i] ~ MvNormal(μ = m, Σ = C)
```
both correspond to `MvNormalMeanCovariance`, but the first one fails when looking for a missing interface.
