### ISSUE TITLE
Use of `end` in LHS indexing

### ISSUE THREAD

**Issue by bartvanerp** [ReactiveBayes/GraphPPL.jl#205]
As already discussed with @wouterwln, the following snippet causes issues
```Julia
s[end] ~ distribution
```
It makes total sense as the size of `s` can change, but hinders user-friendliness a bit. Especially when adding a goal prior the above syntax used to be quite common.

A solution could be to change `s[end]` to `s[lastindex(s)]`

**Comment by wouterwln** [comment]
`FunctionalIndex`es are only used in the constraints language, this syntax Bart highlights will go to:
```julia
s = GraphPPL.getorcreate!(__model__, __context__, :s, end)
```
from the top of my head. We can call `lastindex(s)` instead and change it on a syntax level, but shouldn't be too difficult of a change imo

**Comment by bvdmitri** [comment]
> FunctionalIndexes are only used in the constraints language
That is not true, they are used in the `@model` macro as well.
