### ISSUE TITLE
Inference using a DataArray

### ISSUE THREAD

**Issue by Dhuige** [ReactiveBayes/GraphPPL.jl#23]
It might be nice to infer data using an array. Slicing the array into a vector in the model able to read it out

By which I mean that one would be able to use an array given the following:

![image](https://user-images.githubusercontent.com/31347265/213677251-5b8ce74e-5150-4efe-9b51-c9d63edd555f.png)

**Comment by bvdmitri** [comment]
@albertpod @wouterwln @Dhuige We may consider this improvement in the next iteration of the `GraphPPL.jl`, should be doable imo

**Comment by bvdmitri** [comment]
ping @wouterwln

**Comment by wouterwln** [comment]
I think this is possible in `RxInfer` 3.0 onward, right?

**Comment by bvdmitri** [comment]
I'm not entirely sure, better to add a test for it
