### ISSUE TITLE
Constraint specified in `where` clause is not parsed

### ISSUE THREAD

**Issue by wouterwln** [ReactiveBayes/GraphPPL.jl#91]
Is directly stored but is not parsed like constraints in constraint macro is parsed.

**Comment by wouterwln** [comment]
@bvdmitri we might not even implement this, I think it's a significant burden to make with little benefit

**Comment by bvdmitri** [comment]
We might not implement this at this stage, lets keep this open and see if we actually need it in the future. If no-one complains, we will close the issue.

**Comment by wouterwln** [comment]
@bvdmitri let's close? I think `GraphPPL.default_constraints` covers this particular use case
